[theme]
primaryColor = "#00d4c8"
backgroundColor = "#071A2F"
secondaryBackgroundColor = "#0a1628"
textColor = "#f5f0e3"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
